### PR TITLE
Retakes pistols nades

### PR DESCRIPTION
**Pull request by BrutalCSEjziponken**
Adds Pistol menu (!guns) and nades (flash, smoke, HE) and removes helmet. I basically just copied code from splewis and BatMen to create this.

This has no AWP or any other weapons. I'm using it on my Pistols only server.

P250
HKP2000
USP-S
Deagle
Glock
Fiveseven

### CODE REVIEW

**Comment by BatMen** [comment]
Maybe i'm going to create some cvars to put in your server.cfg like 
retakes_allow_awp
retakes_allow_nades
retakes_allow_nades_hegrenade
retakes_allow_nades_...
retakes_allow_primary_weapon
...

What do you think?

**Comment by spot88** [comment]
Is this added to splewis retake plugin? Or do i have to do anything to make it work. Onlything holding me back to change to splewis plugin, is the grunrounds.

**Comment by BatMen** [comment]
You can check this repository if you want custom weapon allocator.
https://github.com/BatMen/csgo-retakes-splewis-convar-weapon-allocator
Installation instruction are on main page.

**Comment by splewis** [comment]
I guess I'll get around to putting this into the public repository. Thanks for the contribution.

**Pull request merged**
