### PR TITLE
Add vertigo spawns

### PR DESCRIPTION
**Pull request by Fohdeesha**
It may not be perfect, but here's the spawnfile for de_vertigo we've created for use on our retake server that has worked well for our use. As de_vertigo is now in the active duty map pool and ESEA has added it to their competitive map pool, I feel it warrants inclusion in the project's "example" spawn files

### CODE REVIEW

**Comment by splewis** [comment]
I haven't look at these at all; but I suppose some spawns are better than none. Thanks!

**Comment by borzaka** [comment]
@Fohdeesha Maybe do you have an updated version of Vertigo spawns? Because a map is changed so much since, many spawn points are not working/valid anymore. Thx.

**Comment by Fohdeesha** [comment]
My CS team just finished an hour or so of testing new/fixed vertigo spawns. Will create a new PR.

**Comment by Fohdeesha** [comment]
@borzaka you''ll find new/fixed spawns here https://github.com/splewis/csgo-retakes/pull/194

**Comment by borzaka** [comment]
Nice work, thank you @Fohdeesha!

**Pull request merged**
