### PR TITLE
Update de_dust2 spawns for new map

### PR DESCRIPTION
**Pull request by Technoblazed**
A port of dust2 spawns readded according to previous positions

### CODE REVIEW

**Comment by splewis** [comment]
Thanks!

**Comment by wasyady** [comment]
CTs stucking in midbox when bomb planted on B
Anybody has got resolvation this problem ?

**Comment by Technoblazed** [comment]
Redownload the spawns

**Comment by wasyady** [comment]
I think it's because of a yesterday upgrade because it has not been a problem so far.

**Comment by Technoblazed** [comment]
Are you using the new spawns?

**Comment by wasyady** [comment]
Yes, but today Valve modificated mid and others.

**Comment by Technoblazed** [comment]
I'll go test the spawns and move them if they need it.

**Comment by wasyady** [comment]
Thanks in advance!

**Comment by Technoblazed** [comment]
Wait, which spawn is broken?

**Comment by wasyady** [comment]
Mid CT spawns at bomb on B.

**Comment by Technoblazed** [comment]
https://github.com/splewis/csgo-retakes/pull/120

**Pull request merged**
