### PR TITLE
Weapon choices and more

### PR DESCRIPTION
**Pull request by BatMen**
Hello,

This is my first pull request (and my first fork).

I don't know if you will like my features. **Keep it simple, stupid**, I try.

I only change retakes_standardallocator.sp

Features are :
 - Smokegrenade is forbidden on TSide. Flashbang given instead.
 - Options /guns and /gun added
 - Molotov/Incgrenade added
 - /guns menu give options for secondary weapons
 - First 5 rounds are gun rounds

I'm not sure but it seems like the first player of each side get AWP if he chose it. I only add binary random result before. Only 1 AWP per side. But he gets his AWP only if binary result is 1. A round can be played with no AWP.

Give me some feedbacks and **thank you for your plugin**

### CODE REVIEW

**Comment by splewis** [comment]
First, thanks for actually making things happen yourself. Too many people just rely on my to make their servers happen, so well done taking initiative.

But first, here's the way my retakes plugin is written; it has:
- a base plugin (retakes.smx) that does basic team logic/spawns and provides functions for other plugins to modify the behavior
- as you saw, one of those functions is Retakes_SetPlayerInfo which can set what weapons/equipment a player gets, my option allocator plugin (retakes_standardallocator.smx) uses this for some simple weapon logic with a few nades and AWPs

So, anyone else could write their own allocator plugin, name it whatever they want, and delete retakes_standardallocator.smx and it'll work. The purpose of me splitting things up like this was because I didn't want to be the sole creator of the weapon balance.

Therefore, to add your custom weapon behavior you don't actually have to fork anything. You could make your own repository with just a file retakes_batmanweapons.sp and ``#include "retakes.inc"``, compile it, and it would work on a server that has the base retakes plugin.

My point is that you don't actually have to fork anything - you could start from retakes_standardallocator (like you did) and tweak it to your liking and let it stand alone as its work. (similar to how I assume people have sourcemod on their server, you could assume they have my base retakes plugin)

**Comment by BatMen** [comment]
Thank you for your explanations.

As you know, when you search RETAKES plugins on internet, you have barely two choices : 
 - your plugin
 - the one I first use which rewrites your retakes.sp file almost entirely and does not use allocator.sp (SQLite/Mysql spawns...)

I think that the majority of CSGO server owners only search for the magic SMX file. They don't know how to compile it.
*I personnaly had some trouble to handle dependencies because this was the first time i compile sourcemod code*

You may receive a lot of requests to change your weapon allocator like people want it to be.

I fully understand that this is not the core of the plugin and that everybody can rewrite this part. My version is not what everybody wants either.

I'm always referencing to your project in my readme file because i don't want to get credit for that. I barely change 20 lines of code.

Your solution to include an alternative weapon allocator in your readme file is fine.

I'm going to create a new depository with only retakes_standardallocator.sp and the linux SMX version and i will send it if you want to change your readme. (you do not need to).

You can close the pull request.

Thank you for your time.

**Comment by BatMen** [comment]
[There is my custom Weapon allocator](https://github.com/BatMen/csgo-retakes-splewis-convar-weapon-allocator). Many cvars added. If you are still ok to add it into your files. The plugin has been tested for 4 hours, 1 hour private to check cvars and the other to play :+1: 


If you want me to rename something (*like your name in my repository*), tell me.

Thank you.

**Comment by BrutalCSEjziponken** [comment]
This one with cvars sounds awesome.

**Comment by splewis** [comment]
I'm going to go ahead and close this since it's not really merge-able anyway. (since you overwrote the README)

Since the plugin is fairly complex, and could potentially get more complex, I think it's just better to leave it in a separate repository.

**Pull request closed without merging**
